export const GET_USERS = 'GET_USERS';
export const FILTER_USERS = 'FILTER_USERS';
export const GET_NEXT_USERS = 'GET_NEXT_USERS';
export const GET_PREVIOUS_USERS = 'GET_PREVIOUS_USERS';
export const CHANGE_USER_DATA_FROM_LIST = 'CHANGE_USER_DATA_FROM_LIST';
export const USERS_LOADED = 'USERS_LOADED';
